# Generated by Django 3.1.5 on 2021-01-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_box_color',
            field=models.CharField(default='220, 220, 220', max_length=25),
        ),
    ]
