# Generated by Django 3.1.5 on 2021-02-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20210125_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(default='telefon1234'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='nazwa', max_length=50),
        ),
    ]
